apiVersion: v1
kind: ServiceAccount
metadata:
  name:  sa-project
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  rb-project
  namespace: default
subjects:
- kind : ServiceAccount
  name:  sa-project
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name:  view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-proje
  namespace: default
spec:
  serviceAccountName: sa-project
  containers:
    - image:  ozgurozturknet/k8s:latest
      name:  projectcontainer
      ports:
      - containerPort: 80
    